export const products = [
  {
    id: 1,
    name: "MacBook Pro",
    category: "Laptop",
    brand: "Apple",
    price: 189999,
  },
  {
    id: 2,
    name: "Dell XPS 13",
    category: "Laptop",
    brand: "Dell",
    price: 129999,
  },
  {
    id: 3,
    name: "iPhone 16",
    category: "Mobile",
    brand: "Apple",
    price: 89999,
  },
  {
    id: 4,
    name: "Galaxy S25",
    category: "Mobile",
    brand: "Samsung",
    price: 85999,
  },
  {
    id: 5,
    name: "Sony WH-1000XM5",
    category: "Headphones",
    brand: "Sony",
    price: 29999,
  },
  {
    id: 6,
    name: "AirPods Pro",
    category: "Headphones",
    brand: "Apple",
    price: 24999,
  },
  {
    id: 7,
    name: "Logitech MX Master 3S",
    category: "Mouse",
    brand: "Logitech",
    price: 9999,
  },
  {
    id: 8,
    name: "Keychron K2",
    category: "Keyboard",
    brand: "Keychron",
    price: 8499,
  },
  {
    id: 9,
    name: "Samsung Odyssey G5",
    category: "Monitor",
    brand: "Samsung",
    price: 26999,
  },
  {
    id: 10,
    name: "iPad Air",
    category: "Tablet",
    brand: "Apple",
    price: 59999,
  },
];
